name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Version
        id: version
        uses: paulhatch/semantic-version@v5.4.0
        with:
          version_format: "${major}.${minor}.${patch}"
          tag_prefix: ""
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4.2.0
        with:
          dotnet-version: 3.1.100
      - name: Build Packages
        run: bash build.sh
        env:
          DOTNET_CLI_TELEMETRY_OPTOUT: 1
          VERSION: ${{ steps.version.outputs.version }}.${{ steps.version.outputs.increment }}
          PACKAGE_VERSION: ${{ steps.version.outputs.version }}-preview.${{ steps.version.outputs.increment }}
      - name: Run Unit Tests
        run: dotnet test -c Release --no-build --no-restore src/VaultSharpDataProtection.Test/.
      - name: Store Image Artifact
        uses: actions/upload-artifact@v4
        with:
          name: packages.tar.gz
          path: /tmp/artifacts/packages.tar.gz
  publish-preview:
    name: Publish Prerelease Packages
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download Packages Artifact
        uses: actions/download-artifact@v4
        with:
          name: packages.tar.gz
          path: ./packages
      - name: Extract Packages and Publish Preview
        run: |
          tar xvfz ./packages/packages.tar.gz
          for f in *.nupkg
          do
            curl -vX PUT -u "PaulHatch:${{ secrets.GITHUB_TOKEN }}" -F package=@$f https://nuget.pkg.github.com/PaulHatch/
          done